run-python-script:
  script:
  - 'python -m pip install --upgrade pip

    pip install -r requirements.txt

    python3 -m pip install --upgrade pip setuptools

    sudo apt-get update -y

    sudo apt-get install git ffmpeg libsm6 libxext6 -y

    git lfs install

    '
  - git clone https://huggingface.co/immich-app/LABSE-Vit-L-14
  - python build_rknn.py LABSE-Vit-L-14/textual/model.onnx
  - rm LABSE-Vit-L-14/textual/model.rknn
  - python build_rknn.py LABSE-Vit-L-14/visual/model.onnx
  - rm LABSE-Vit-L-14/visual/model.rknn
  - rm -rf LABSE-Vit-L-14
  - git clone https://huggingface.co/immich-app/XLM-Roberta-Large-Vit-B-16Plus
  - python build_rknn.py XLM-Roberta-Large-Vit-B-16Plus/textual/model.onnx
  - rm XLM-Roberta-Large-Vit-B-16Plus/textual/model.rknn
  - python build_rknn.py XLM-Roberta-Large-Vit-B-16Plus/visual/model.onnx
  - rm XLM-Roberta-Large-Vit-B-16Plus/visual/model.rknn
  - rm -rf XLM-Roberta-Large-Vit-B-16Plus
  - git clone https://huggingface.co/immich-app/XLM-Roberta-Large-Vit-B-32
  - python build_rknn.py XLM-Roberta-Large-Vit-B-32/textual/model.onnx
  - rm XLM-Roberta-Large-Vit-B-32/textual/model.rknn
  - python build_rknn.py XLM-Roberta-Large-Vit-B-32/visual/model.onnx
  - rm XLM-Roberta-Large-Vit-B-32/visual/model.rknn
  - rm -rf XLM-Roberta-Large-Vit-B-32
  - git clone https://huggingface.co/immich-app/XLM-Roberta-Large-Vit-L-14
  - python build_rknn.py XLM-Roberta-Large-Vit-L-14/textual/model.onnx
  - rm XLM-Roberta-Large-Vit-L-14/textual/model.rknn
  - python build_rknn.py XLM-Roberta-Large-Vit-L-14/visual/model.onnx
  - rm XLM-Roberta-Large-Vit-L-14/visual/model.rknn
  - rm -rf XLM-Roberta-Large-Vit-L-14
  - git clone https://huggingface.co/immich-app/RN101__openai
  - python build_rknn.py RN101__openai/textual/model.onnx
  - rm RN101__openai/textual/model.rknn
  - python build_rknn.py RN101__openai/visual/model.onnx
  - rm RN101__openai/visual/model.rknn
  - rm -rf RN101__openai
  - git clone https://huggingface.co/immich-app/RN101__yfcc15m
  - python build_rknn.py RN101__yfcc15m/textual/model.onnx
  - rm RN101__yfcc15m/textual/model.rknn
  - python build_rknn.py RN101__yfcc15m/visual/model.onnx
  - rm RN101__yfcc15m/visual/model.rknn
  - rm -rf RN101__yfcc15m
  - git clone https://huggingface.co/immich-app/RN50__cc12m
  - python build_rknn.py RN50__cc12m/textual/model.onnx
  - rm RN50__cc12m/textual/model.rknn
  - python build_rknn.py RN50__cc12m/visual/model.onnx
  - rm RN50__cc12m/visual/model.rknn
  - rm -rf RN50__cc12m
  - git clone https://huggingface.co/immich-app/RN50__openai
  - python build_rknn.py RN50__openai/textual/model.onnx
  - rm RN50__openai/textual/model.rknn
  - python build_rknn.py RN50__openai/visual/model.onnx
  - rm RN50__openai/visual/model.rknn
  - rm -rf RN50__openai
  - git clone https://huggingface.co/immich-app/RN50__yfcc15m
  - python build_rknn.py RN50__yfcc15m/textual/model.onnx
  - rm RN50__yfcc15m/textual/model.rknn
  - python build_rknn.py RN50__yfcc15m/visual/model.onnx
  - rm RN50__yfcc15m/visual/model.rknn
  - rm -rf RN50__yfcc15m
  - git clone https://huggingface.co/immich-app/RN50x16__openai
  - python build_rknn.py RN50x16__openai/textual/model.onnx
  - rm RN50x16__openai/textual/model.rknn
  - python build_rknn.py RN50x16__openai/visual/model.onnx
  - rm RN50x16__openai/visual/model.rknn
  - rm -rf RN50x16__openai
  - git clone https://huggingface.co/immich-app/RN50x4__openai
  - python build_rknn.py RN50x4__openai/textual/model.onnx
  - rm RN50x4__openai/textual/model.rknn
  - python build_rknn.py RN50x4__openai/visual/model.onnx
  - rm RN50x4__openai/visual/model.rknn
  - rm -rf RN50x4__openai
  - git clone https://huggingface.co/immich-app/RN50x64__openai
  - python build_rknn.py RN50x64__openai/textual/model.onnx
  - rm RN50x64__openai/textual/model.rknn
  - python build_rknn.py RN50x64__openai/visual/model.onnx
  - rm RN50x64__openai/visual/model.rknn
  - rm -rf RN50x64__openai
  - git clone https://huggingface.co/immich-app/ViT-B-16-SigLIP-256__webli
  - python build_rknn.py ViT-B-16-SigLIP-256__webli/textual/model.onnx
  - rm ViT-B-16-SigLIP-256__webli/textual/model.rknn
  - python build_rknn.py ViT-B-16-SigLIP-256__webli/visual/model.onnx
  - rm ViT-B-16-SigLIP-256__webli/visual/model.rknn
  - rm -rf ViT-B-16-SigLIP-256__webli
  - git clone https://huggingface.co/immich-app/ViT-B-16-SigLIP-384__webli
  - python build_rknn.py ViT-B-16-SigLIP-384__webli/textual/model.onnx
  - rm ViT-B-16-SigLIP-384__webli/textual/model.rknn
  - python build_rknn.py ViT-B-16-SigLIP-384__webli/visual/model.onnx
  - rm ViT-B-16-SigLIP-384__webli/visual/model.rknn
  - rm -rf ViT-B-16-SigLIP-384__webli
  - git clone https://huggingface.co/immich-app/ViT-B-16-SigLIP-512__webli
  - python build_rknn.py ViT-B-16-SigLIP-512__webli/textual/model.onnx
  - rm ViT-B-16-SigLIP-512__webli/textual/model.rknn
  - python build_rknn.py ViT-B-16-SigLIP-512__webli/visual/model.onnx
  - rm ViT-B-16-SigLIP-512__webli/visual/model.rknn
  - rm -rf ViT-B-16-SigLIP-512__webli
  - git clone https://huggingface.co/immich-app/ViT-B-16-SigLIP-i18n-256__webli
  - python build_rknn.py ViT-B-16-SigLIP-i18n-256__webli/textual/model.onnx
  - rm ViT-B-16-SigLIP-i18n-256__webli/textual/model.rknn
  - python build_rknn.py ViT-B-16-SigLIP-i18n-256__webli/visual/model.onnx
  - rm ViT-B-16-SigLIP-i18n-256__webli/visual/model.rknn
  - rm -rf ViT-B-16-SigLIP-i18n-256__webli
  - git clone https://huggingface.co/immich-app/ViT-B-16-SigLIP__webli
  - python build_rknn.py ViT-B-16-SigLIP__webli/textual/model.onnx
  - rm ViT-B-16-SigLIP__webli/textual/model.rknn
  - python build_rknn.py ViT-B-16-SigLIP__webli/visual/model.onnx
  - rm ViT-B-16-SigLIP__webli/visual/model.rknn
  - rm -rf ViT-B-16-SigLIP__webli
  - git clone https://huggingface.co/immich-app/ViT-B-16-plus-240__laion400m_e31
  - python build_rknn.py ViT-B-16-plus-240__laion400m_e31/textual/model.onnx
  - rm ViT-B-16-plus-240__laion400m_e31/textual/model.rknn
  - python build_rknn.py ViT-B-16-plus-240__laion400m_e31/visual/model.onnx
  - rm ViT-B-16-plus-240__laion400m_e31/visual/model.rknn
  - rm -rf ViT-B-16-plus-240__laion400m_e31
  - git clone https://huggingface.co/immich-app/ViT-B-16-plus-240__laion400m_e32
  - python build_rknn.py ViT-B-16-plus-240__laion400m_e32/textual/model.onnx
  - rm ViT-B-16-plus-240__laion400m_e32/textual/model.rknn
  - python build_rknn.py ViT-B-16-plus-240__laion400m_e32/visual/model.onnx
  - rm ViT-B-16-plus-240__laion400m_e32/visual/model.rknn
  - rm -rf ViT-B-16-plus-240__laion400m_e32
  - git clone https://huggingface.co/immich-app/ViT-B-16__laion400m_e31
  - python build_rknn.py ViT-B-16__laion400m_e31/textual/model.onnx
  - rm ViT-B-16__laion400m_e31/textual/model.rknn
  - python build_rknn.py ViT-B-16__laion400m_e31/visual/model.onnx
  - rm ViT-B-16__laion400m_e31/visual/model.rknn
  - rm -rf ViT-B-16__laion400m_e31
  - git clone https://huggingface.co/immich-app/ViT-B-16__laion400m_e32
  - python build_rknn.py ViT-B-16__laion400m_e32/textual/model.onnx
  - rm ViT-B-16__laion400m_e32/textual/model.rknn
  - python build_rknn.py ViT-B-16__laion400m_e32/visual/model.onnx
  - rm ViT-B-16__laion400m_e32/visual/model.rknn
  - rm -rf ViT-B-16__laion400m_e32
  - git clone https://huggingface.co/immich-app/ViT-B-16__openai
  - python build_rknn.py ViT-B-16__openai/textual/model.onnx
  - rm ViT-B-16__openai/textual/model.rknn
  - python build_rknn.py ViT-B-16__openai/visual/model.onnx
  - rm ViT-B-16__openai/visual/model.rknn
  - rm -rf ViT-B-16__openai
  - git clone https://huggingface.co/immich-app/ViT-B-32__laion2b-s34b-b79k
  - python build_rknn.py ViT-B-32__laion2b-s34b-b79k/textual/model.onnx
  - rm ViT-B-32__laion2b-s34b-b79k/textual/model.rknn
  - python build_rknn.py ViT-B-32__laion2b-s34b-b79k/visual/model.onnx
  - rm ViT-B-32__laion2b-s34b-b79k/visual/model.rknn
  - rm -rf ViT-B-32__laion2b-s34b-b79k
  - git clone https://huggingface.co/immich-app/ViT-B-32__laion2b_e16
  - python build_rknn.py ViT-B-32__laion2b_e16/textual/model.onnx
  - rm ViT-B-32__laion2b_e16/textual/model.rknn
  - python build_rknn.py ViT-B-32__laion2b_e16/visual/model.onnx
  - rm ViT-B-32__laion2b_e16/visual/model.rknn
  - rm -rf ViT-B-32__laion2b_e16
  - git clone https://huggingface.co/immich-app/ViT-B-32__laion400m_e31
  - python build_rknn.py ViT-B-32__laion400m_e31/textual/model.onnx
  - rm ViT-B-32__laion400m_e31/textual/model.rknn
  - python build_rknn.py ViT-B-32__laion400m_e31/visual/model.onnx
  - rm ViT-B-32__laion400m_e31/visual/model.rknn
  - rm -rf ViT-B-32__laion400m_e31
  - git clone https://huggingface.co/immich-app/ViT-B-32__laion400m_e32
  - python build_rknn.py ViT-B-32__laion400m_e32/textual/model.onnx
  - rm ViT-B-32__laion400m_e32/textual/model.rknn
  - python build_rknn.py ViT-B-32__laion400m_e32/visual/model.onnx
  - rm ViT-B-32__laion400m_e32/visual/model.rknn
  - rm -rf ViT-B-32__laion400m_e32
  - git clone https://huggingface.co/immich-app/ViT-B-32__openai
  - python build_rknn.py ViT-B-32__openai/textual/model.onnx
  - rm ViT-B-32__openai/textual/model.rknn
  - python build_rknn.py ViT-B-32__openai/visual/model.onnx
  - rm ViT-B-32__openai/visual/model.rknn
  - rm -rf ViT-B-32__openai
  - git clone https://huggingface.co/immich-app/ViT-H-14-378-quickgelu__dfn5b
  - python build_rknn.py ViT-H-14-378-quickgelu__dfn5b/textual/model.onnx
  - rm ViT-H-14-378-quickgelu__dfn5b/textual/model.rknn
  - python build_rknn.py ViT-H-14-378-quickgelu__dfn5b/visual/model.onnx
  - rm ViT-H-14-378-quickgelu__dfn5b/visual/model.rknn
  - rm -rf ViT-H-14-378-quickgelu__dfn5b
  - git clone https://huggingface.co/immich-app/ViT-H-14-quickgelu__dfn5b
  - python build_rknn.py ViT-H-14-quickgelu__dfn5b/textual/model.onnx
  - rm ViT-H-14-quickgelu__dfn5b/textual/model.rknn
  - python build_rknn.py ViT-H-14-quickgelu__dfn5b/visual/model.onnx
  - rm ViT-H-14-quickgelu__dfn5b/visual/model.rknn
  - rm -rf ViT-H-14-quickgelu__dfn5b
  - git clone https://huggingface.co/immich-app/ViT-H-14__laion2b-s32b-b79k
  - python build_rknn.py ViT-H-14__laion2b-s32b-b79k/textual/model.onnx
  - rm ViT-H-14__laion2b-s32b-b79k/textual/model.rknn
  - python build_rknn.py ViT-H-14__laion2b-s32b-b79k/visual/model.onnx
  - rm ViT-H-14__laion2b-s32b-b79k/visual/model.rknn
  - rm -rf ViT-H-14__laion2b-s32b-b79k
  - git clone https://huggingface.co/immich-app/ViT-L-14-336__openai
  - python build_rknn.py ViT-L-14-336__openai/textual/model.onnx
  - rm ViT-L-14-336__openai/textual/model.rknn
  - python build_rknn.py ViT-L-14-336__openai/visual/model.onnx
  - rm ViT-L-14-336__openai/visual/model.rknn
  - rm -rf ViT-L-14-336__openai
  - git clone https://huggingface.co/immich-app/ViT-L-14-quickgelu__dfn2b
  - python build_rknn.py ViT-L-14-quickgelu__dfn2b/textual/model.onnx
  - rm ViT-L-14-quickgelu__dfn2b/textual/model.rknn
  - python build_rknn.py ViT-L-14-quickgelu__dfn2b/visual/model.onnx
  - rm ViT-L-14-quickgelu__dfn2b/visual/model.rknn
  - rm -rf ViT-L-14-quickgelu__dfn2b
  - git clone https://huggingface.co/immich-app/ViT-L-14__laion2b-s32b-b82k
  - python build_rknn.py ViT-L-14__laion2b-s32b-b82k/textual/model.onnx
  - rm ViT-L-14__laion2b-s32b-b82k/textual/model.rknn
  - python build_rknn.py ViT-L-14__laion2b-s32b-b82k/visual/model.onnx
  - rm ViT-L-14__laion2b-s32b-b82k/visual/model.rknn
  - rm -rf ViT-L-14__laion2b-s32b-b82k
  - git clone https://huggingface.co/immich-app/ViT-L-14__laion400m_e31
  - python build_rknn.py ViT-L-14__laion400m_e31/textual/model.onnx
  - rm ViT-L-14__laion400m_e31/textual/model.rknn
  - python build_rknn.py ViT-L-14__laion400m_e31/visual/model.onnx
  - rm ViT-L-14__laion400m_e31/visual/model.rknn
  - rm -rf ViT-L-14__laion400m_e31
  - git clone https://huggingface.co/immich-app/ViT-L-14__laion400m_e32
  - python build_rknn.py ViT-L-14__laion400m_e32/textual/model.onnx
  - rm ViT-L-14__laion400m_e32/textual/model.rknn
  - python build_rknn.py ViT-L-14__laion400m_e32/visual/model.onnx
  - rm ViT-L-14__laion400m_e32/visual/model.rknn
  - rm -rf ViT-L-14__laion400m_e32
  - git clone https://huggingface.co/immich-app/ViT-L-14__openai
  - python build_rknn.py ViT-L-14__openai/textual/model.onnx
  - rm ViT-L-14__openai/textual/model.rknn
  - python build_rknn.py ViT-L-14__openai/visual/model.onnx
  - rm ViT-L-14__openai/visual/model.rknn
  - rm -rf ViT-L-14__openai
  - git clone https://huggingface.co/immich-app/ViT-L-16-SigLIP-256__webli
  - python build_rknn.py ViT-L-16-SigLIP-256__webli/textual/model.onnx
  - rm ViT-L-16-SigLIP-256__webli/textual/model.rknn
  - python build_rknn.py ViT-L-16-SigLIP-256__webli/visual/model.onnx
  - rm ViT-L-16-SigLIP-256__webli/visual/model.rknn
  - rm -rf ViT-L-16-SigLIP-256__webli
  - git clone https://huggingface.co/immich-app/ViT-L-16-SigLIP-384__webli
  - python build_rknn.py ViT-L-16-SigLIP-384__webli/textual/model.onnx
  - rm ViT-L-16-SigLIP-384__webli/textual/model.rknn
  - python build_rknn.py ViT-L-16-SigLIP-384__webli/visual/model.onnx
  - rm ViT-L-16-SigLIP-384__webli/visual/model.rknn
  - rm -rf ViT-L-16-SigLIP-384__webli
  - git clone https://huggingface.co/immich-app/ViT-SO400M-14-SigLIP-384__webli
  - python build_rknn.py ViT-SO400M-14-SigLIP-384__webli/textual/model.onnx
  - rm ViT-SO400M-14-SigLIP-384__webli/textual/model.rknn
  - python build_rknn.py ViT-SO400M-14-SigLIP-384__webli/visual/model.onnx
  - rm ViT-SO400M-14-SigLIP-384__webli/visual/model.rknn
  - rm -rf ViT-SO400M-14-SigLIP-384__webli
  - git clone https://huggingface.co/immich-app/ViT-g-14__laion2b-s12b-b42k
  - python build_rknn.py ViT-g-14__laion2b-s12b-b42k/textual/model.onnx
  - rm ViT-g-14__laion2b-s12b-b42k/textual/model.rknn
  - python build_rknn.py ViT-g-14__laion2b-s12b-b42k/visual/model.onnx
  - rm ViT-g-14__laion2b-s12b-b42k/visual/model.rknn
  - rm -rf ViT-g-14__laion2b-s12b-b42k
  - git clone https://huggingface.co/immich-app/nllb-clip-base-siglip__mrl
  - python build_rknn.py nllb-clip-base-siglip__mrl/textual/model.onnx
  - rm nllb-clip-base-siglip__mrl/textual/model.rknn
  - python build_rknn.py nllb-clip-base-siglip__mrl/visual/model.onnx
  - rm nllb-clip-base-siglip__mrl/visual/model.rknn
  - rm -rf nllb-clip-base-siglip__mrl
  - git clone https://huggingface.co/immich-app/nllb-clip-base-siglip__v1
  - python build_rknn.py nllb-clip-base-siglip__v1/textual/model.onnx
  - rm nllb-clip-base-siglip__v1/textual/model.rknn
  - python build_rknn.py nllb-clip-base-siglip__v1/visual/model.onnx
  - rm nllb-clip-base-siglip__v1/visual/model.rknn
  - rm -rf nllb-clip-base-siglip__v1
  - git clone https://huggingface.co/immich-app/nllb-clip-large-siglip__mrl
  - python build_rknn.py nllb-clip-large-siglip__mrl/textual/model.onnx
  - rm nllb-clip-large-siglip__mrl/textual/model.rknn
  - python build_rknn.py nllb-clip-large-siglip__mrl/visual/model.onnx
  - rm nllb-clip-large-siglip__mrl/visual/model.rknn
  - rm -rf nllb-clip-large-siglip__mrl
  - git clone https://huggingface.co/immich-app/nllb-clip-large-siglip__v1
  - python build_rknn.py nllb-clip-large-siglip__v1/textual/model.onnx
  - rm nllb-clip-large-siglip__v1/textual/model.rknn
  - python build_rknn.py nllb-clip-large-siglip__v1/visual/model.onnx
  - rm nllb-clip-large-siglip__v1/visual/model.rknn
  - rm -rf nllb-clip-large-siglip__v1
  - git clone https://huggingface.co/immich-app/xlm-roberta-base-ViT-B-32__laion5b_s13b_b90k
  - python build_rknn.py xlm-roberta-base-ViT-B-32__laion5b_s13b_b90k/textual/model.onnx
  - rm xlm-roberta-base-ViT-B-32__laion5b_s13b_b90k/textual/model.rknn
  - python build_rknn.py xlm-roberta-base-ViT-B-32__laion5b_s13b_b90k/visual/model.onnx
  - rm xlm-roberta-base-ViT-B-32__laion5b_s13b_b90k/visual/model.rknn
  - rm -rf xlm-roberta-base-ViT-B-32__laion5b_s13b_b90k
  - git clone https://huggingface.co/immich-app/xlm-roberta-large-ViT-H-14__frozen_laion5b_s13b_b90k
  - python build_rknn.py xlm-roberta-large-ViT-H-14__frozen_laion5b_s13b_b90k/textual/model.onnx
  - rm xlm-roberta-large-ViT-H-14__frozen_laion5b_s13b_b90k/textual/model.rknn
  - python build_rknn.py xlm-roberta-large-ViT-H-14__frozen_laion5b_s13b_b90k/visual/model.onnx
  - rm xlm-roberta-large-ViT-H-14__frozen_laion5b_s13b_b90k/visual/model.rknn
  stage: run-python-script
  tags:
  - ubuntu-latest
stages:
- run-python-script
