jobs:
  run-python-script:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Install dependencies
      run: 'python3 -m pip install --upgrade pip setuptools

        pip install -r requirements.txt

        sudo apt-get update -y

        sudo apt-get install git libsm6 -y

        git lfs install

        '
    - name: Clone model
      run: 'git clone https://huggingface.co/immich-app/ViT-B-32__openai --depth 1 '
    - name: Run textual build script
      run: python build_rknn.py ViT-B-32__openai/textual/model.onnx
    - name: Upload textual artifact
      uses: actions/upload-artifact@v4
      with:
        name: ViT-B-32__openai-textual.rknn
        path: ViT-B-32__openai/textual/model.rknn
    - name: Remove uploaded textual model
      run: rm ViT-B-32__openai/textual/model.rknn
    - name: Run visual build script
      run: python build_rknn.py ViT-B-32__openai/visual/model.onnx
    - name: Upload visual artifact
      uses: actions/upload-artifact@v4
      with:
        name: ViT-B-32__openai-visual.rknn
        path: ViT-B-32__openai/visual/model.rknn
    - name: Remove uploaded visual model
      run: rm ViT-B-32__openai/visual/model.rknn
name: Run Python Build Script
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

# Last updated at: 2024-11-30 13:37:45 using build_yaml.py, do not edit manually