jobs:
  run-python-script:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Install dependencies
      run: 'python3 -m pip install --upgrade pip setuptools

        pip install -r requirements.txt

        sudo apt-get update -y

        sudo apt-get install git libsm6 -y

        git lfs install

        '
    - name: Clone model ViT-B-32__openai
      run: git clone https://huggingface.co/immich-app/ViT-B-32__openai --depth 1
        ViT-B-32__openai
    - name: Run textual build script for ViT-B-32__openai on rk3562
      run: python3 build_rknn.py ViT-B-32__openai/textual/model.onnx rk3562
    - name: Upload textual artifact for ViT-B-32__openai on rk3562
      uses: actions/upload-artifact@v4
      with:
        name: ViT-B-32__openai-textual-rk3562.rknn
        path: ViT-B-32__openai/textual/model_rk3562.rknn
    - name: Remove uploaded textual model for ViT-B-32__openai on rk3562
      run: rm ViT-B-32__openai/textual/model_rk3562.rknn
    - name: Run visual build script for ViT-B-32__openai on rk3562
      run: python3 build_rknn.py ViT-B-32__openai/visual/model.onnx rk3562
    - name: Upload visual artifact for ViT-B-32__openai on rk3562
      uses: actions/upload-artifact@v4
      with:
        name: ViT-B-32__openai-visual-rk3562.rknn
        path: ViT-B-32__openai/visual/model_rk3562.rknn
    - name: Remove uploaded visual model for ViT-B-32__openai on rk3562
      run: rm ViT-B-32__openai/visual/model_rk3562.rknn
    - name: Run textual build script for ViT-B-32__openai on rk3566
      run: python3 build_rknn.py ViT-B-32__openai/textual/model.onnx rk3566
    - name: Upload textual artifact for ViT-B-32__openai on rk3566
      uses: actions/upload-artifact@v4
      with:
        name: ViT-B-32__openai-textual-rk3566.rknn
        path: ViT-B-32__openai/textual/model_rk3566.rknn
    - name: Remove uploaded textual model for ViT-B-32__openai on rk3566
      run: rm ViT-B-32__openai/textual/model_rk3566.rknn
    - name: Run visual build script for ViT-B-32__openai on rk3566
      run: python3 build_rknn.py ViT-B-32__openai/visual/model.onnx rk3566
    - name: Upload visual artifact for ViT-B-32__openai on rk3566
      uses: actions/upload-artifact@v4
      with:
        name: ViT-B-32__openai-visual-rk3566.rknn
        path: ViT-B-32__openai/visual/model_rk3566.rknn
    - name: Remove uploaded visual model for ViT-B-32__openai on rk3566
      run: rm ViT-B-32__openai/visual/model_rk3566.rknn
    - name: Run textual build script for ViT-B-32__openai on rk3568
      run: python3 build_rknn.py ViT-B-32__openai/textual/model.onnx rk3568
    - name: Upload textual artifact for ViT-B-32__openai on rk3568
      uses: actions/upload-artifact@v4
      with:
        name: ViT-B-32__openai-textual-rk3568.rknn
        path: ViT-B-32__openai/textual/model_rk3568.rknn
    - name: Remove uploaded textual model for ViT-B-32__openai on rk3568
      run: rm ViT-B-32__openai/textual/model_rk3568.rknn
    - name: Run visual build script for ViT-B-32__openai on rk3568
      run: python3 build_rknn.py ViT-B-32__openai/visual/model.onnx rk3568
    - name: Upload visual artifact for ViT-B-32__openai on rk3568
      uses: actions/upload-artifact@v4
      with:
        name: ViT-B-32__openai-visual-rk3568.rknn
        path: ViT-B-32__openai/visual/model_rk3568.rknn
    - name: Remove uploaded visual model for ViT-B-32__openai on rk3568
      run: rm ViT-B-32__openai/visual/model_rk3568.rknn
    - name: Run textual build script for ViT-B-32__openai on rk3576
      run: python3 build_rknn.py ViT-B-32__openai/textual/model.onnx rk3576
    - name: Upload textual artifact for ViT-B-32__openai on rk3576
      uses: actions/upload-artifact@v4
      with:
        name: ViT-B-32__openai-textual-rk3576.rknn
        path: ViT-B-32__openai/textual/model_rk3576.rknn
    - name: Remove uploaded textual model for ViT-B-32__openai on rk3576
      run: rm ViT-B-32__openai/textual/model_rk3576.rknn
    - name: Run visual build script for ViT-B-32__openai on rk3576
      run: python3 build_rknn.py ViT-B-32__openai/visual/model.onnx rk3576
    - name: Upload visual artifact for ViT-B-32__openai on rk3576
      uses: actions/upload-artifact@v4
      with:
        name: ViT-B-32__openai-visual-rk3576.rknn
        path: ViT-B-32__openai/visual/model_rk3576.rknn
    - name: Remove uploaded visual model for ViT-B-32__openai on rk3576
      run: rm ViT-B-32__openai/visual/model_rk3576.rknn
    - name: Run textual build script for ViT-B-32__openai on rk3588
      run: python3 build_rknn.py ViT-B-32__openai/textual/model.onnx rk3588
    - name: Upload textual artifact for ViT-B-32__openai on rk3588
      uses: actions/upload-artifact@v4
      with:
        name: ViT-B-32__openai-textual-rk3588.rknn
        path: ViT-B-32__openai/textual/model_rk3588.rknn
    - name: Remove uploaded textual model for ViT-B-32__openai on rk3588
      run: rm ViT-B-32__openai/textual/model_rk3588.rknn
    - name: Run visual build script for ViT-B-32__openai on rk3588
      run: python3 build_rknn.py ViT-B-32__openai/visual/model.onnx rk3588
    - name: Upload visual artifact for ViT-B-32__openai on rk3588
      uses: actions/upload-artifact@v4
      with:
        name: ViT-B-32__openai-visual-rk3588.rknn
        path: ViT-B-32__openai/visual/model_rk3588.rknn
    - name: Remove uploaded visual model for ViT-B-32__openai on rk3588
      run: rm ViT-B-32__openai/visual/model_rk3588.rknn
name: Run Python Build Script
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

# Last updated at: 2025-01-11 16:51:38 using build_yaml.py, do not edit manually