jobs:
  run-python-script:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Install dependencies
      run: 'python3 -m pip install --upgrade pip setuptools

        pip install -r requirements.txt

        sudo apt-get update -y

        sudo apt-get install git libsm6 -y

        git lfs install

        '
    - name: Clone model buffalo_l
      run: git clone https://huggingface.co/immich-app/buffalo_l --depth 1 buffalo_l
    - name: Run detection build script for buffalo_l on rk3566
      run: python3 build_rknn.py buffalo_l/detection/model.onnx rk3566
    - name: Upload detection artifact for buffalo_l on rk3566
      uses: actions/upload-artifact@v4
      with:
        name: buffalo_l-detection-rk3566.rknn
        path: buffalo_l/detection/model_rk3566.rknn
    - name: Remove uploaded detection model for buffalo_l on rk3566
      run: rm buffalo_l/detection/model_rk3566.rknn
    - name: Run recognition build script for buffalo_l on rk3566
      run: python3 build_rknn.py buffalo_l/recognition/model.onnx rk3566
    - name: Upload recognition artifact for buffalo_l on rk3566
      uses: actions/upload-artifact@v4
      with:
        name: buffalo_l-recognition-rk3566.rknn
        path: buffalo_l/recognition/model_rk3566.rknn
    - name: Remove uploaded recognition model for buffalo_l on rk3566
      run: rm buffalo_l/recognition/model_rk3566.rknn
    - name: Run detection build script for buffalo_l on rk3588
      run: python3 build_rknn.py buffalo_l/detection/model.onnx rk3588
    - name: Upload detection artifact for buffalo_l on rk3588
      uses: actions/upload-artifact@v4
      with:
        name: buffalo_l-detection-rk3588.rknn
        path: buffalo_l/detection/model_rk3588.rknn
    - name: Remove uploaded detection model for buffalo_l on rk3588
      run: rm buffalo_l/detection/model_rk3588.rknn
    - name: Run recognition build script for buffalo_l on rk3588
      run: python3 build_rknn.py buffalo_l/recognition/model.onnx rk3588
    - name: Upload recognition artifact for buffalo_l on rk3588
      uses: actions/upload-artifact@v4
      with:
        name: buffalo_l-recognition-rk3588.rknn
        path: buffalo_l/recognition/model_rk3588.rknn
    - name: Remove uploaded recognition model for buffalo_l on rk3588
      run: rm buffalo_l/recognition/model_rk3588.rknn
name: Run Python Build Script
on:
  pull_request:
    branches:
    - facial
  push:
    branches:
    - facial

# Last updated at: 2025-01-11 02:02:24 using build_yaml.py, do not edit manually