jobs:
  run-python-script:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Install dependencies
      run: 'python3 -m pip install --upgrade pip setuptools

        pip install -r requirements.txt

        sudo apt-get update -y

        sudo apt-get install git libsm6 -y

        git lfs install

        '
    - name: Clone model
      run: 'git clone https://huggingface.co/immich-app/buffalo_1 --depth 1 '
    - name: Run textual build script
      run: python build_rknn.py buffalo_1/textual/model.onnx
    - name: Upload textual artifact
      uses: actions/upload-artifact@v4
      with:
        name: buffalo_1-textual.rknn
        path: buffalo_1/textual/model.rknn
    - name: Remove uploaded textual model
      run: rm buffalo_1/textual/model.rknn
    - name: Run visual build script
      run: python build_rknn.py buffalo_1/visual/model.onnx
    - name: Upload visual artifact
      uses: actions/upload-artifact@v4
      with:
        name: buffalo_1-visual.rknn
        path: buffalo_1/visual/model.rknn
    - name: Remove uploaded visual model
      run: rm buffalo_1/visual/model.rknn
    - name: RM cloned repo
      run: rm -rf buffalo_1
    - name: Clone model
      run: 'git clone https://huggingface.co/immich-app/antelopev2 --depth 1 '
    - name: Run textual build script
      run: python build_rknn.py antelopev2/textual/model.onnx
    - name: Upload textual artifact
      uses: actions/upload-artifact@v4
      with:
        name: antelopev2-textual.rknn
        path: antelopev2/textual/model.rknn
    - name: Remove uploaded textual model
      run: rm antelopev2/textual/model.rknn
    - name: Run visual build script
      run: python build_rknn.py antelopev2/visual/model.onnx
    - name: Upload visual artifact
      uses: actions/upload-artifact@v4
      with:
        name: antelopev2-visual.rknn
        path: antelopev2/visual/model.rknn
    - name: Remove uploaded visual model
      run: rm antelopev2/visual/model.rknn
    - name: RM cloned repo
      run: rm -rf antelopev2
    - name: Clone model
      run: 'git clone https://huggingface.co/immich-app/buffalo_s --depth 1 '
    - name: Run textual build script
      run: python build_rknn.py buffalo_s/textual/model.onnx
    - name: Upload textual artifact
      uses: actions/upload-artifact@v4
      with:
        name: buffalo_s-textual.rknn
        path: buffalo_s/textual/model.rknn
    - name: Remove uploaded textual model
      run: rm buffalo_s/textual/model.rknn
    - name: Run visual build script
      run: python build_rknn.py buffalo_s/visual/model.onnx
    - name: Upload visual artifact
      uses: actions/upload-artifact@v4
      with:
        name: buffalo_s-visual.rknn
        path: buffalo_s/visual/model.rknn
    - name: Remove uploaded visual model
      run: rm buffalo_s/visual/model.rknn
    - name: RM cloned repo
      run: rm -rf buffalo_s
    - name: Clone model
      run: 'git clone https://huggingface.co/immich-app/buffalo_m --depth 1 '
    - name: Run textual build script
      run: python build_rknn.py buffalo_m/textual/model.onnx
    - name: Upload textual artifact
      uses: actions/upload-artifact@v4
      with:
        name: buffalo_m-textual.rknn
        path: buffalo_m/textual/model.rknn
    - name: Remove uploaded textual model
      run: rm buffalo_m/textual/model.rknn
    - name: Run visual build script
      run: python build_rknn.py buffalo_m/visual/model.onnx
    - name: Upload visual artifact
      uses: actions/upload-artifact@v4
      with:
        name: buffalo_m-visual.rknn
        path: buffalo_m/visual/model.rknn
    - name: Remove uploaded visual model
      run: rm buffalo_m/visual/model.rknn
    - name: RM cloned repo
      run: rm -rf buffalo_m
    - name: Clone model
      run: 'git clone https://huggingface.co/immich-app/buffalo_l_batch --depth 1 '
    - name: Run textual build script
      run: python build_rknn.py buffalo_l_batch/textual/model.onnx
    - name: Upload textual artifact
      uses: actions/upload-artifact@v4
      with:
        name: buffalo_l_batch-textual.rknn
        path: buffalo_l_batch/textual/model.rknn
    - name: Remove uploaded textual model
      run: rm buffalo_l_batch/textual/model.rknn
    - name: Run visual build script
      run: python build_rknn.py buffalo_l_batch/visual/model.onnx
    - name: Upload visual artifact
      uses: actions/upload-artifact@v4
      with:
        name: buffalo_l_batch-visual.rknn
        path: buffalo_l_batch/visual/model.rknn
    - name: Remove uploaded visual model
      run: rm buffalo_l_batch/visual/model.rknn
    - name: RM cloned repo
      run: rm -rf buffalo_l_batch
    - name: Clone model
      run: 'git clone https://huggingface.co/immich-app/scrfd_34g_gnkps --depth 1 '
    - name: Run textual build script
      run: python build_rknn.py scrfd_34g_gnkps/textual/model.onnx
    - name: Upload textual artifact
      uses: actions/upload-artifact@v4
      with:
        name: scrfd_34g_gnkps-textual.rknn
        path: scrfd_34g_gnkps/textual/model.rknn
    - name: Remove uploaded textual model
      run: rm scrfd_34g_gnkps/textual/model.rknn
    - name: Run visual build script
      run: python build_rknn.py scrfd_34g_gnkps/visual/model.onnx
    - name: Upload visual artifact
      uses: actions/upload-artifact@v4
      with:
        name: scrfd_34g_gnkps-visual.rknn
        path: scrfd_34g_gnkps/visual/model.rknn
    - name: Remove uploaded visual model
      run: rm scrfd_34g_gnkps/visual/model.rknn
name: Run Python Build Script
on:
  pull_request:
    branches:
    - facial
  push:
    branches:
    - facial

# Last updated at: 2024-11-28 09:52:01 using build_yaml.py, do not edit manually